apiVersion: apps/v1
kind: Deployment
metadata:
    name: backend-deploy
    labels:
        app: backend-deploy
spec:
    replicas: 1
    selector:
        matchLabels:
            app: backend-deploy
    template:
        metadata:
            name: backend-deploy
            labels:
                app: backend-deploy
        spec:
            containers:
                - name: backend
                  image: eric-araujo/orchestrator-service
                  imagePullPolicy: Never
                  envFrom:
                      - configMapRef:
                            name: backend-configmap
                  ports:
                      - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
    name: backend-service
spec:
    type: NodePort
    selector:
        app: backend-deploy
    ports:
        - protocol: TCP
          port: 8000
          targetPort: 8080
