kind: ConfigMap
apiVersion: v1
metadata:
    name: backend-configmap
    namespace: default
data:
    # Configuration Values are stored as key-value pairs
    ASSISTANT_API: http://ms-sp-assistant-api-dev.mybluemix.net/api/v1/assistant
    WATSON_API_KEY: API_KEY
    ASSISTANT_ID: ASSISTANT_API
    WATSON_API_URL: https://api.us-south.assistant.watson.cloud.ibm.com/instances/URL
    PORT: '8080'
