import { Message } from 'assistant/interfaces';
import { AxiosResponse } from 'axios';
import {
    ActionPayload,
    CreateIncidentResponse,
    IncidentQueryReponse,
    ResolveIncidentResponse,
    ServiceOpeningRequestResponse,
    ServiceRequestQueryResponse,
} from './interfaces';

export const mockedData: Message = {
    generic: [{ response_type: 'text', text: 'teste' }],
    skillsContext: {
        action: [
            {
                action: 'create-inc',
                data: {
                    ID: 'ID1',
                    Contact: '9',
                    Title: 'TESTE',
                    Service: 'OPEN',
                    Category: 'OPEN',
                    Area: 'S',
                    Subarea: 'F',
                    ProblemType: 'I',
                    UserPriority: 2,
                    SeverityCode: 2,
                    AffectedCI: '',
                    OperUpdatedBy: 'O',
                    WhoContactIdentificatin: 'O',
                    WhoContactName: 'OPER_XXXX',
                    WhoContactEmail: 'OPER_XXXX@XXXX.COM.BR',
                    WhoContactPhone: 'XXXX',
                    Description: ['linha1', 'linha2'],
                },
            },
            {
                action: 'query-inc',
                data: {
                    incId: 'ID1',
                },
            },
            {
                action: 'open-rs',
                data: {
                    Category: 'R',
                    Subcategory: 'R',
                    FluxoDeNegocio: '2',
                    Impact: '2',
                    MeioContato: 'Telephone',
                    RequestedFor: 'OPER',
                    Model: '-00',
                    CurrentPhase: 'FASE DE EXECUCAO',
                    IDExterno: '9043',
                    Title: 'R',
                    Description: 'Descrição linha1\nDescrição linha2',
                    Checklist: [
                        '',
                        'Ver campo descrição',
                        'Ver campo descrição',
                    ],
                },
            },
            {
                action: 'query-rs',
                data: {
                    rsId: 'RS6667400',
                },
            },
            {
                action: 'solve-inc',
                data: {
                    Replicar: 'false',
                    OperUpdatedBy: 'OPER_XXXX',
                    ResolutionCode: 'R',
                    ResolutionFixType: 'temporary',
                    OperationalDevice: 'false',
                    InicioIndisponibilidade: '2021-05-18T12:45:54-03:00',
                    FimIndisponibilidade: '2021-05-18T13:45:54-03:00',
                    DataSolucao: '2021-05-28T11:08:47-03:00',
                    AffectedCIFind: 'false',
                    Explanation: [
                        'Explanation:',
                        'Explanation:',
                    ],
                    OrientacaoUsuario: [
                        'OrientacaoUsuario:1',
                        'OrientacaoUsuario:2',
                    ],
                },
            },
        ],
    },
};

export const actionPayload: ActionPayload[] = [
    {
        message: 'INC-CREATE-SUCCESS',
        payload: {
            success: true,
            data: {
                IncidentManagementPadraoDS: {
                    Area: 'S',
                    AssignmentGroup:
                        'D',
                    Category: 'O',
                    CodigoJuncao: '00000',
                    Contact: 'OPER_XXXX',
                    Description: ['linha1', 'linha2'],
                    Diagnostico: 'NAO INFORMADO',
                    DiferentContact: true,
                    ForWhomCompany: 'B',
                    ForWhomContactName: 'OPER_XXXX',
                    ForWhomDept: '00000',
                    ForWhomDiferentContact: true,
                    ForWhomEmail: 'OPER',
                    ID: 'ID1',
                    OpenTime: '2021-05-28T18:43:35+00:00',
                    OpenedBy: 'OPER',
                    OperUpdatedBy: 'OPER',
                    PriorityCode: 3,
                    ProblemType: 'INDISPONIVEL',
                    RDMRelated: false,
                    Service: 'OPEN',
                    SeverityCode: 2,
                    Status: 'DIRECIONADO',
                    Subarea: 'F',
                    TicketOwner: 'O',
                    TipoAmbiente: 'PRODUCAO',
                    Title: 'TESTE',
                    UpdatedBy: 'OPER_XXXX',
                    UpdatedTime: '2021-05-28T18:43:35+00:00',
                    UserPriority: 2,
                    WhoContactEmail: 'OPER_XXXX',
                    WhoContactIdentificatin: 'OPER_XXXX',
                    WhoContactName: 'OPER_XXXX',
                    WhoContactPhone: 'OPER_XXXX',
                },
                Messages: [
                    'Brazil/East 28/05/2021 15:43:37: O incidente IN4082118 foi aberto por OPER_XXXX',
                ],
                data: {
                    Messages: [
                        'Brazil/East 28/05/2021 15:43:37: O incidente IN4082118 foi aberto por OPER_XXXX',
                    ],
                },

                ReturnCode: 0,
            },
        },
    },
    {
        message: 'INC-QUERY-SUCCESS',
        payload: {
            success: true,
            data: {
                content: [
                    {
                        IncidentManagementPadraoDS: {
                            Action: 'ALTERAR',
                            Area: 'S',
                            Assignee: 'O',
                            AssignmentGroup:
                                'D',
                            AssignmentGroupAnt:
                                'D',
                            Category: 'OPEN',
                            CodigoJuncao: '00000',
                            Contact: 'OPER',
                            Description: ['linha1', 'linha2'],
                            Diagnostico: 'NAO INFORMADO',
                            DiferentContact: true,
                            ForWhomCompany: 'B',
                            ForWhomContactName: 'OPER',
                            ForWhomDept: '00000',
                            ForWhomDiferentContact: true,
                            ForWhomEmail: 'TESTE@.COM.BR',
                            ForWhomExtention: '123',
                            ForWhomPhone: '123',
                            GrupoProprietario:
                                'D',
                            ID: 'ID1',
                            JournalUpdates: [
                                'ATUALIZADO POR OPER EM 28/5/2021 ÀS 15:34:21',
                                'LINHA 1',
                                'LINHA2',
                                null,
                                '--------------------------------------------------------------------------------------------------------------',
                                'ATUALIZADO POR OPER EM 28/5/2021 ÀS 15:20:32',
                                'LINHA 1',
                                'LINHA2',
                                null,
                                '--------------------------------------------------------------------------------------------------------------',
                                'ATUALIZADO POR OPER EM 28/5/2021 ÀS 15:16:50',
                                'LINHA 1',
                                'LINHA2',
                                null,
                                '--------------------------------------------------------------------------------------------------------------',
                                'ATUALIZADO POR OPER EM 28/5/2021 ÀS 15:16:22',
                                'LINHA 1',
                                'LINHA2',
                                null,
                                '--------------------------------------------------------------------------------------------------------------',
                            ],
                            LastJournalUpdates: [
                                null,
                                null,
                                '---------------------------------------------------------------------------------------',
                                '29/05/2021 03:16:02 DEADLINE ALERT',
                                '***ALERT***',
                            ],
                            OpenTime: '2021-05-28T18:15:59+00:00',
                            OpenedBy: 'OPER',
                            OperUpdatedBy: 'OPER',
                            PriorityCode: 3,
                            ProblemType: 'LENTIDAO / DEGRADADO',
                            RDMRelated: false,
                            Replicar: false,
                            Service: 'OPEN',
                            SeverityCode: 2,
                            Status: 'EM TRATAMENTO',
                            Subarea: 'F',
                            TicketOwner: 'OPER',
                            TipoAmbiente: 'PRODUCAO',
                            Title: 'TESTE',
                            UpdatedBy: 'problem',
                            UpdatedTime: '2021-05-29T06:16:04+00:00',
                            UserPriority: 2,
                            WhoContactEmail: 'OPER',
                            WhoContactIdentificatin: 'OPER',
                            WhoContactName: 'OPER',
                            WhoContactPhone: 'OPER',
                        },
                    },
                ],
                Messages: [
                    'Brazil/East 28/05/2021 15:43:37: O incidente IN4082118 foi aberto por OPER_XXXX',
                ],
                ReturnCode: 0,
            },
        },
    },
    {
        message: 'RS-OPEN-SUCCESS',
        payload: {
            success: true,
            data: {
                Messages: [
                    'Requisi��o RS6667400 fase FASE DE REGISTRO aberta por OPER.',
                ],
                ReqInternalToolsPadraoREST: {
                    Category: 'R',
                    Checklist: [
                        null,
                        'Ver campo descri��o',
                        'Ver campo descri��o',
                        'Ver campo descri��o',
                        'Ver campo descri��o',
                    ],
                    ChecklistPergunta: [
                        'OBSERVA��O: ""',
                        'Nome?',
                        'Caminho?',
                        'Qual',
                        'Dat?',
                        'Logs ?',
                        'Caix?',
                    ],
                    CurrentPhase: 'FASE DE EXECUCAO',
                    Description: ['Descri��o linha1', 'Descri��o linha2'],
                    FimAtendimento: '2021-07-07T19:27:07+00:00',
                    FluxoDeNegocio: 2,
                    ForWhomContactName: 'OPER',
                    ForWhomDept: '00000',
                    ForWhomExtension: '0000',
                    ForWhomPhone: '0000',
                    IDExterno: '9043',
                    Impact: 2,
                    MeioContato: 'Telephone',
                    Model: '00',
                    Number: 'RS6667400',
                    OpenedBy: 'OA',
                    PhaseDesc: 'F',
                    RequestedFor: 'O',
                    Subcategory: 'R',
                    Title: 'R',
                },
                ReturnCode: 0,
            },
        },
    },
    {
        message: 'RS-QUERY-SUCCESS',
        payload: {
            success: true,
            data: {
                Messages: [],
                ReqInternalToolsPadraoREST: {
                    Category: 'R',
                    Checklist: [
                        null,
                        'Ver campo descri��o',
                        'Ver campo descri��o',
                        'Ver campo descri��o',
                        'Ver campo descri��o',
                    ],
                    ChecklistPergunta: [
                        'OBSERVA��O: ""',
                        'N?',
                        'C?',
                        'Qu?',
                        'D',
                        'L?',
                        'Ca?',
                    ],
                    CurrentPhase: 'FASE DE EXECUCAO',
                    Description: ['Descri��o linha1', 'Descri��o linha2'],
                    FimAtendimento: '2021-07-07T19:27:07+00:00',
                    FluxoDeNegocio: 2,
                    ForWhomContactName: 'OPER',
                    ForWhomDept: '00000',
                    ForWhomExtension: '0000',
                    ForWhomPhone: '0000',
                    IDExterno: '9043',
                    Impact: 2,
                    MeioContato: 'Telephone',
                    Model: '00',
                    Number: 'RS6667400',
                    OpenedBy: 'OPER',
                    PhaseDesc: 'FASE DE EXECUCAO',
                    RequestedFor: 'OPER',
                    Subcategory: 'R',
                    Title: 'R',
                },
                ReturnCode: 0,
            },
        },
    },
    {
        message: 'INC-SOLVE-SUCCESS',
        payload: {
            success: true,
            data: {
                IncidentManagementPadraoDS: {
                    Action: 'TRATAR INCIDENTE',
                    AffectedCIFind: false,
                    Area: 'S',
                    Assignee: 'OPER_XXXX',
                    AssignmentGroup:
                        'D',
                    AssignmentGroupAnt:
                        'D',
                    Category: 'OPEN',
                    CodigoJuncao: '00000',
                    Contact: 'OPER',
                    DataSolucao: '2021-05-28T14:08:47+00:00',
                    Description: ['linha1', 'linha2'],
                    Diagnostico: 'NAO INFORMADO',
                    DiferentContact: true,
                    Explanation: [
                        'Explanation:T',
                        'Explanation:T',
                    ],
                    FimIndisponibilidade: '2021-05-18T16:45:54+00:00',
                    ForWhomCompany: 'B',
                    ForWhomContactName: 'OPER',
                    ForWhomDept: '00000',
                    ForWhomDiferentContact: true,
                    ForWhomEmail: 'TESTE@.COM.BR',
                    ForWhomExtention: '123',
                    ForWhomPhone: '123',
                    GrupoProprietario:
                        'D',
                    ID: 'ID1',
                    InicioIndisponibilidade: '2021-05-18T15:45:54+00:00',
                    JournalUpdates: [
                        'ATUALIZADO EM 28/5/2021 �S 11:07:56',
                        'LINHA 1',
                        'LINHA2',
                        null,
                        '--------------------------------------------------------------------------------------------------------------',
                    ],
                    LastJournalUpdates: [
                        'ATUALIZADO POR OPER EM 28/05/2021 11:07:56',
                        null,
                        '---------------------------------------------------------------------------------------',
                        'TRATAMENTO DO INCIDENTE',
                        'LINHA2',
                    ],
                    OpenTime: '2021-05-28T14:07:07+00:00',
                    OpenedBy: 'OPER',
                    OperUpdatedBy: 'OPER',
                    OperationalDevice: false,
                    OrientacaoUsuario: [
                        'OrientacaoUsuario:N',
                        'OrientacaoUsuario:N',
                    ],
                    PriorityCode: 3,
                    ProblemType: 'INDISPONIVEL',
                    RDMRelated: false,
                    Replicar: false,
                    ResolutionCode: 'R',
                    ResolutionFixType: 'temporary',
                    Service: 'OPEN',
                    SeverityCode: 2,
                    Status: 'RESOLVIDO',
                    Subarea: 'F',
                    TipoAmbiente: 'PRODUCAO',
                    Title: 'TESTE',
                    UpdatedBy: 'OPER',
                    UpdatedTime: '2021-05-28T14:08:55+00:00',
                    UserPriority: 2,
                    WhoContactEmail: 'OPER',
                    WhoContactIdentificatin: 'OPER',
                    WhoContactName: 'OPER',
                    WhoContactPhone: 'OPER',
                },
                Messages: [
                    'O incidente IN4082047 foi solucionado por OPER.',
                    'O incidente IN4082047 foi solucionado por OPER.',
                    'Brazil/East 28/05/2021 11:08:55: O incidente IN4082047 foi resolvido por OPER',
                ],
                ReturnCode: 0,
            },
        },
    },
];

export const actionPayloadError: ActionPayload[] = [
    {
        message: 'RS-OPEN-FAILURE',
        payload: {
            success: false,
            data: {
                ReturnCode: 0,
            },
        },
    },
    {
        message: 'RS-QUERY-FAILURE',
        payload: {
            success: false,
            data: {
                ReturnCode: 0,
            },
        },
    },
    {
        message: 'INC-CREATE-FAILURE',
        payload: {
            success: false,
            data: {
                ReturnCode: 0,
            },
        },
    },
    {
        message: 'INC-QUERY-FAILURE',
        payload: {
            success: false,
            data: {
                ReturnCode: 0,
            },
        },
    },
    {
        message: 'INC-SOLVE-FAILURE',
        payload: {
            success: false,
            data: {
                ReturnCode: 0,
            },
        },
    },
];
export const queryInResponse: AxiosResponse<IncidentQueryReponse> = {
    headers: {},
    status: 200,
    statusText: 'OK',
    data: {
        content: [
            {
                IncidentManagementPadraoDS: {
                    Action: 'A',
                    Area: 'S',
                    Assignee: 'OPER',
                    AssignmentGroup:
                        'D',
                    AssignmentGroupAnt:
                        'D',
                    Category: 'O',
                    CodigoJuncao: '00000',
                    Contact: 'OPER',
                    Description: ['linha1', 'linha2'],
                    Diagnostico: 'NAO INFORMADO',
                    DiferentContact: true,
                    ForWhomCompany: 'B',
                    ForWhomContactName: 'OPER',
                    ForWhomDept: '00000',
                    ForWhomDiferentContact: true,
                    ForWhomEmail: 'TESTE@.COM.BR',
                    ForWhomExtention: '123',
                    ForWhomPhone: '123',
                    GrupoProprietario:
                        'D',
                    ID: 'ID1',
                    JournalUpdates: [
                        'ATUALIZADO POR OPER EM 28/5/2021 ÀS 15:34:21',
                        'LINHA 1',
                        'LINHA2',
                        null,
                        '--------------------------------------------------------------------------------------------------------------',
                        'ATUALIZADO POR OPER EM 28/5/2021 ÀS 15:20:32',
                        'LINHA 1',
                        'LINHA2',
                        null,
                        '--------------------------------------------------------------------------------------------------------------',
                        'ATUALIZADO POR OPER EM 28/5/2021 ÀS 15:16:50',
                        'LINHA 1',
                        'LINHA2',
                        null,
                        '--------------------------------------------------------------------------------------------------------------',
                        'ATUALIZADO POR OPER EM 28/5/2021 ÀS 15:16:22',
                        'LINHA 1',
                        'LINHA2',
                        null,
                        '--------------------------------------------------------------------------------------------------------------',
                    ],
                    LastJournalUpdates: [
                        null,
                        null,
                        '---------------------------------------------------------------------------------------',
                        '29/05/2021 03:16:02 DEADLINE ALERT',
                        '***ALERT***',
                    ],
                    OpenTime: '2021-05-28T18:15:59+00:00',
                    OpenedBy: 'O',
                    OperUpdatedBy: 'O',
                    PriorityCode: 3,
                    ProblemType: 'L',
                    RDMRelated: false,
                    Replicar: false,
                    Service: 'O',
                    SeverityCode: 2,
                    Status: 'EM TRATAMENTO',
                    Subarea: 'F',
                    TicketOwner: 'O',
                    TipoAmbiente: 'PRODUCAO',
                    Title: 'T',
                    UpdatedBy: 'problem',
                    UpdatedTime: '2021-05-29T06:16:04+00:00',
                    UserPriority: 2,
                    WhoContactEmail: 'O',
                    WhoContactIdentificatin: 'O',
                    WhoContactName: 'O',
                    WhoContactPhone: 'O',
                },
            },
        ],
        Messages: [
            'Brazil/East 28/05/2021 15:43:37: O incidente IN4082118 foi aberto por OPER',
        ],
        ReturnCode: 0,
    },
    config: undefined,
};
export const queryInResponseError: AxiosResponse<IncidentQueryReponse> = {
    headers: {},
    status: 200,
    statusText: 'OK',
    data: {
        content: [
            {
                IncidentManagementPadraoDS: {
                    Action: 'A',
                    Area: 'S',
                    Assignee: 'O',
                    AssignmentGroup:
                        'DO',
                    AssignmentGroupAnt:
                        'D',
                    Category: 'OPEN',
                    CodigoJuncao: '00000',
                    Contact: 'OP',
                    Description: ['linha1', 'linha2'],
                    Diagnostico: 'NAO INFORMADO',
                    DiferentContact: true,
                    ForWhomCompany: 'B',
                    ForWhomContactName: 'OP',
                    ForWhomDept: '00000',
                    ForWhomDiferentContact: true,
                    ForWhomEmail: 'TESTE@.COM.BR',
                    ForWhomExtention: '123',
                    ForWhomPhone: '123',
                    GrupoProprietario:
                        'D',
                    ID: 'ID1',
                    JournalUpdates: [
                        'ATUALIZADO POR OPER EM 28/5/2021 ÀS 15:34:21',
                        'LINHA 1',
                        'LINHA2',
                        null,
                        '--------------------------------------------------------------------------------------------------------------',
                        'ATUALIZADO POR OPER EM 28/5/2021 ÀS 15:20:32',
                        'LINHA 1',
                        'LINHA2',
                        null,
                        '--------------------------------------------------------------------------------------------------------------',
                        'ATUALIZADO POR OPER EM 28/5/2021 ÀS 15:16:50',
                        'LINHA 1',
                        'LINHA2',
                        null,
                        '--------------------------------------------------------------------------------------------------------------',
                        'ATUALIZADO POR OPER EM 28/5/2021 ÀS 15:16:22',
                        'LINHA 1',
                        'LINHA2',
                        null,
                        '--------------------------------------------------------------------------------------------------------------',
                    ],
                    LastJournalUpdates: [
                        null,
                        null,
                        '---------------------------------------------------------------------------------------',
                        '29/05/2021 03:16:02 DEADLINE ALERT',
                        '***ALERT***',
                    ],
                    OpenTime: '2021-05-28T18:15:59+00:00',
                    OpenedBy: 'OPER',
                    OperUpdatedBy: 'OPER',
                    PriorityCode: 3,
                    ProblemType: 'LENTIDAO / DEGRADADO',
                    RDMRelated: false,
                    Replicar: false,
                    Service: 'OPEN',
                    SeverityCode: 2,
                    Status: 'EM TRATAMENTO',
                    Subarea: 'F',
                    TicketOwner: 'OP',
                    TipoAmbiente: 'PRODUCAO',
                    Title: 'TESTE',
                    UpdatedBy: 'problem',
                    UpdatedTime: '2021-05-29T06:16:04+00:00',
                    UserPriority: 2,
                    WhoContactEmail: 'OPER',
                    WhoContactIdentificatin: 'OPER',
                    WhoContactName: 'OPER',
                    WhoContactPhone: 'OPER',
                },
            },
        ],
        Messages: [
            'Brazil/East 28/05/2021 15:43:37: O incidente IN4082118 foi aberto por OPER',
        ],
        ReturnCode: 1,
    },
    config: undefined,
};

export const serviceQueryResponse: AxiosResponse<ServiceRequestQueryResponse> =
    {
        headers: {},
        status: 200,
        statusText: 'OK',
        data: {
            Messages: [],
            ReqInternalToolsPadraoREST: {
                Category: 'R',
                Checklist: [
                    null,
                    'Ver campo descri��o',
                    'Ver campo descri��o',
                    'Ver campo descri��o',
                    'Ver campo descri��o',
                ],
                ChecklistPergunta: [
                    'OBSERVA��O: "."',
                    'N',
                    'C',
                    'Q',
                    'D',
                    'L?',
                    'C',
                ],
                CurrentPhase: 'FASE DE EXECUCAO',
                Description: ['Descri��o linha1', 'Descri��o linha2'],
                FimAtendimento: '2021-07-07T19:27:07+00:00',
                FluxoDeNegocio: 2,
                ForWhomContactName: 'OPER',
                ForWhomDept: '00000',
                ForWhomExtension: '000',
                ForWhomPhone: '-0000',
                IDExterno: '9043',
                Impact: 2,
                MeioContato: 'Telephone',
                Model: '00',
                Number: 'RS6667400',
                OpenedBy: 'OPER',
                PhaseDesc: 'FASE DE EXECUCAO',
                RequestedFor: 'OPER',
                Subcategory: 'R',
                Title: 'R',
            },
            ReturnCode: 0,
        },
        config: undefined,
    };
